name: Build App

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci # Adjust this based on your project's dependencies

      - name: Build and Package
        run: npm run build

      - name: Zip artifacts
        run: |
          cd dist
          for dir in */; do
            zip -r "${dir%/}.zip" "$dir"
          done
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files in directory
        run: |
          for file in $(find path/to/your/directory -type f); do
            echo "Uploading $file"
            echo "::set-output name=file::$file"
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-artifacts
          path: ${{ steps.build.outputs.file }}